config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'foods#index'
  resources :foods, except: :show do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '野菜' },
    { id: 3, name: '肉' },
    { id: 4, name: '魚介' },
    { id: 5, name: '米・パン・麺類' },
    { id: 6, name: '卵・チーズ・乳製品' },
    { id: 7, name: '飲料' },
    { id: 8, name: '調味料' },
    { id: 9, name: '粉類' },
    { id: 10, name: '乾物' },
    { id: 11, name: '豆腐・納豆・漬物' },
    { id: 12, name: '惣菜・レトルト・冷凍' },
    { id: 13, name: '果物' },
    { id: 14, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :foods
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :unit
  belongs_to :category

  with_options presence: true do
    validates :name
    validates :bb_date

    validates :number, numericality: { message: 'は半角数字で入力してください' },
                       inclusion: { in: 1..10_000, message: 'は1〜10,000以内で入力してください' }

    with_options numericality: { other_than: 1, message: 'を選択してください' } do
      validates :unit_id
      validates :category_id
    end
  end
end

app/models/unit.rb
class Unit < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '個' },
    { id: 3, name: 'パック' },
    { id: 4, name: '袋' },
    { id: 5, name: 'g' },
    { id: 6, name: '尾' },
    { id: 7, name: '切れ' },
    { id: 8, name: '玉' },
    { id: 9, name: '枚' }
  ]

  include ActiveHash::Associations
  has_many :foods
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods

  validates :nickname, presence: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英数字で入力してください' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Basic認証導入
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_food, only: [:edit, :update, :destroy]
  before_action :move_to_root_path, only: :edit
  before_action :set_search, only: [:index, :search]

  def index
    @foods = Food.includes(:user).order('bb_date')
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @food.update(food_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @food.destroy
    redirect_to root_path
  end

  # 検索機能
  def search
  end

  private

  def food_params
    params.require(:food).permit(:name, :number, :unit_id, :bb_date, :category_id).merge(user_id: current_user.id)
  end

  def set_food
    @food = Food.find(params[:id])
  end

  def move_to_root_path
    @food = Food.find(params[:id])
    redirect_to root_path unless current_user.id == @food.user.id
  end

  def set_search
    @search = Food.ransack(params[:q])
    @search_foods = @search.result(distinct: true).includes(:user).order('bb_date')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/edit.html.erb
<div class='edit-contents'>
  <div class='new-sub-contents'>
    <div class='new-header'>
        <%= link_to 'Reizo', root_path, class:'new-top-btn' %>
    </div>
    <div class='new-main'>
      <h1 class='edit-title'>
        食材編集ページ
      </h1>
      <div class='new-form'>
        <%= form_with(model: @food, local: true) do |f| %>
          <div class='form-group'>
            <div class='text-title'>
              食材名
              <span class='required'>必須</span>
            </div>
            <%= f.text_area :name, class:'new-text', placeholder: '食材名' %>
            <%= render 'shared/error_messages', model: f.object, attribute: :name %>
          </div>

          <div class='form-group'>
            <div class='text-title'>
              数量
              <span class='required'>必須</span>
            </div>
              <%= f.text_area :number, class:'new-text', placeholder: '半角数字', autofocus: true %>
              <%= render 'shared/error_messages', model: f.object, attribute: :number %>
          </div>

          <div class='form-group'>
            <div class='text-title'>
              単位
              <span class='required'>必須</span>
            </div>
            <%= f.collection_select(:unit_id, Unit.all, :id, :name, {}, {class:"select-unit"}) %>
            <%= render 'shared/error_messages', model: f.object, attribute: :unit_id %>
          </div>

          <div class='form-group'>
            <div class='text-title'>
              カテゴリー
              <span class='required'>必須</span>
            </div>
            <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box"}) %>
            <%= render 'shared/error_messages', model: f.object, attribute: :category_id %>
          </div>

          <div class='form-group'>
            <div class='text-title'>
              賞味期限
              <span class='required'>必須</span>
            </div>
            <div class='bb-date-form'>
              <%= f.date_field :bb_date, class: 'select-bb-date' %>
              <%= render 'shared/error_messages', model: f.object, attribute: :bb_date %>
            </div>
          </div>
          <div class='submit-form'>
            <%= f.submit '変更する', class:'submit-btn' %>
            <%= link_to '削除する', food_path, method: :delete, class:'delete-btn' %>
            <%= link_to '戻る', root_path, class: 'back-btn' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/foods/index.html.erb
<%= render "shared/header" %>

<div class="main">
  <div class='contents'>
    <h1 class="title">
      食材一覧
    </h1>
    <ul class="foods-list">

      <% @foods.each do |food| %>
        <% if user_signed_in? && current_user.id == food.user.id %>
            <li class='food'>
              <%= link_to edit_food_path(food.id), class:'food-link' do %>
                <div class='name'>
                  <%= food.name %>
                </div>
                <div class='number'>
                  <%= food.number %>
                  <%= food.unit.name %>
                </div>
                <div class='bb-date'>
                  賞味期限
                  <span class='day'><%= food.bb_date %></span>
                </div>
              <% end %>
            </li>
        <% end %>
      <% end %>

      <%# ダミーテキスト %>
      <% unless user_signed_in? && current_user.foods.present? %>
        <li class='dummy-text'>
          <div class='name'>
            例) じゃがいも
          </div>
          <div class='number'>
            5個
          </div>
          <div class='bb-date'>
            賞味期限 2020-01-01
          </div>
        </li>
      <% end %>
      <%# /ダミーテキスト %>

    </ul>
  </div>
</div>

<% if user_signed_in?%>
  <%= link_to new_food_path, class:'new-food-btn' do %>
    <div class='new-btn'>
      <span class='new-btn-text'>食材登録</span>
      <%= image_tag 'food-icon.png', class: "new-btn-icon"%>
    </div>
  <% end %>
<% end %>

<%= render "shared/footer" %>

app/views/foods/new.html.erb
<div class='new-contents'>
  <div class='new-sub-contents'>
    <div class='new-header'>
        <%= link_to 'Reizo', root_path, class:'new-top-btn' %>
    </div>
    <div class='new-main'>
      <h1 class='new-title'>
        食材登録
      </h1>
      <div class='new-form'>
        <%= form_with(model: @food, local: true) do |f| %>
          <div class='form-group'>
            <div class='text-title'>
              食材名
              <span class='required'>必須</span>
            </div>
            <%= f.text_area :name, class:'new-text', placeholder: '食材名', autofocus: true %>
            <%= render 'shared/error_messages', model: f.object, attribute: :name %>
          </div>

          <div class='form-group'>
            <div class='text-title'>
              数量
              <span class='required'>必須</span>
            </div>
            <%= f.text_area :number, class:'new-text', placeholder: '半角数字' %>
            <%= render 'shared/error_messages', model: f.object, attribute: :number %>
          </div>

          <div class='form-group'>
            <div class='text-title'>
              単位
              <span class='required'>必須</span>
            </div>
            <%= f.collection_select(:unit_id, Unit.all, :id, :name, {}, {class:"select-unit"}) %>
            <%= render 'shared/error_messages', model: f.object, attribute: :unit_id %>
          </div>

          <div class='form-group'>
            <div class='text-title'>
              カテゴリー
              <span class='required'>必須</span>
            </div>
            <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box"}) %>
            <%= render 'shared/error_messages', model: f.object, attribute: :category_id %>
          </div>

          <div class='form-group'>
            <div class='text-title'>
              賞味期限
              <span class='required'>必須</span>
            </div>
            <div class='bb-date-form'>
              <%= f.date_field :bb_date, class: 'select-bb-date' %>
              <%= render 'shared/error_messages', model: f.object, attribute: :bb_date %>
            </div>
          </div>
          <div class='submit-form'>
            <%= f.submit '登録する', class:'submit-btn' %>
            <%= link_to '戻る', root_path, class: 'back-btn' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/foods/search.html.erb
<%= render "shared/header" %>

<div class="main">
  <div class='contents'>
    <h1 class="title">
      検索結果
    </h1>
      <ul class="foods-list">
        <% @search_foods.each do |food| %>
          <% if user_signed_in? && current_user.id == food.user.id %>
              <li class='food'>
                <%= link_to edit_food_path(food.id), class:'food-link' do %>
                  <div class='name'>
                    <%= food.name %>
                  </div>
                  <div class='number'>
                    <%= food.number %>
                    <%= food.unit.name %>
                  </div>
                  <div class='bb-date'>
                    賞味期限
                    <span class='day'><%= food.bb_date %></span>
                  </div>
                <% end %>
              </li>
          <% end %>
        <% end %>
      </ul>

      <%# 検索結果なしの場合 %>
      <% unless @search_foods.present? %>
          <p>一致する食材がありません</p>
      <% end %>
      <%# /検索結果なしの場合 %>

    <div class='search-back'>
      <%= link_to '戻る', root_path, class: 'search-back-btn' %>
    </div>
  </div>
</div>

<% if user_signed_in?%>
  <%= link_to new_food_path, class:'new-food-btn' do %>
    <div class='new-btn'>
      <span class='new-btn-text'>食材登録</span>
      <%= image_tag 'food-icon.png', class: "new-btn-icon"%>
    </div>
  <% end %>
<% end %>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reizo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages_for(attribute).each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class='top-page-footer'>
  <div class='upper-footer'>
    <%= link_to 'Reizo', root_path, class:'footer-btn'%>
  </div>
  <div class='lower-footer'>
    <ul class='footer-list'>
      <li><%= link_to 'サービス利用規約', "#", class:'footer-link' %></li>
      <li><%= link_to '個人情報保護方針', "#", class:'footer-link' %></li>
      <li><%= link_to '運営会社', "#", class:'footer-link' %></li>
      <li><%= link_to 'お問い合わせ', "#", class:'footer-link' %></li>
    </ul>
  </div>
  <p>
    © Reizo
  </p>
</footer>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='header-contents'>
    <div class='upper-header'>
      <%= link_to 'Reizo', root_path, class:"top-btn" %>
      <ul class='right-list'>
        <% if user_signed_in? %>
          <li><%= link_to current_user.nickname, '#', class:'user-nickname', id: 'header-btn' %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'logout', id: 'header-btn' %></li>
        <% else %>
          <li><%= link_to 'ログイン', new_user_session_path, class:'login', id: 'header-btn'%></li>
          <li><%= link_to "新規登録", new_user_registration_path, class:'sign-up', id: 'header-btn' %></li>
        <% end %>
      </ul>
    </div>
    <div class='app-description'>
      誰でも簡単、食材管理アプリ<br />
      <p class='sub-description'>
        Reizoは冷蔵庫の「食材管理」<br />
        「賞味期限チェック」を一つのアプリで行えます。
      </p>
    </div>
    <div class='foods-search'>
      <%= search_form_for @search, url: search_foods_path, class: 'search-form' do |f| %>
        <%= f.text_field :name_cont, placeholder: "食材を探す", class: 'input-box'%>
        <%= f.collection_select(:category_id_eq, Category.where.not(id: 1), :id, :name, include_blank: 'カテゴリー指定なし', class: "search-category") %>
        <%= f.date_field :bb_date_gteq, class: 'search-bb-date' %>
        <button class="search-button" id="search-btn">
          <%= image_tag "search.png", class:"search-icon" %>
        </button>
      <% end %>
    </div>
  </div>
</header>